name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: "SpaghettDev/4"
assignees:
  - SpaghettDev
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.6.0-beta.1
        - 1.6.0-beta.2
        - 1.6.0-beta.3
        - 1.6.0-beta.4
        - 1.6.1-beta.1
        - 1.6.1-beta.2
        - 1.6.1-beta.3
        - 1.6.2
        - 2.0.0
        - 2.0.1
        - 2.0.2
      default: 10 # Manually increment
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Android (64-bit)
        - Android (32-bit)
        - MacOS
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste the log output that can be found in `Geometry Dash/geode/logs` on Windows and somehwere else in Android (lol). This will be automatically formatted into code, so no need for backticks.
      render: shell
